### ISSUE TITLE
Multiple VHD(X)s

### ISSUE THREAD

**Issue by iainbrighton** [PowerShell/xHyper-V#31]
The xVMHyperV resource only allows assignment of 1 VHD/X file. It would be great if we could support attaching multiple virtual disk files to a VM, but how should this be implemented?

My initial thinking - that wouldn't be a breaking change - would be to change the 'VhdPath' property from a string to an array of strings. This would allow assignment of one or more VHDs without breaking any existing configurations?

**As a side-note: this could also be applied to the 'SwitchName' and 'MACAddress' properties to assign multiple vNICs. I guess that ideally the VM disks and vNICs would be completely separate resources but this would probably break existing functionality?**

**Comment by HemantMahawar** [comment]
I agree with your proposal of making VHDPath as string[]. The only additional ask would be to add an example highlighting this new functionality and updating the description of these parameters.

**Comment by PsPsam** [comment]
I would like to see this implemented! Trying to set up a Lab on a Hyper-V server with DSC to set up the virtual guests and to inject the local DSC for the virtual server. I have the requirement of adding three virtual disk to a server and this is failing. I found the DSC resource cVHDtoVMConnector that allows me to add extra disks. But since that adds disk one by one I for some reason can only add two extra discs. If I add three the server fails to start.

It would be nice if you could create the guest in a off mode. Then add extra resources and then start it. I haven't figured out if that is possible now. I have tried but not been succesfull.

**Comment by Haelters** [comment]
covered in #66 (Extra resource: XVMHardDiskDrive)
